[project]
name = "researchorchestra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "langchain-core",
    "langchain-groq",
    "langgraph",
    "langgraph-checkpoint-postgres",
    "psycopg[binary,pool]",
    "python-dotenv",
    "tavily-python",
    "httpx",
    "beautifulsoup4",
    "readability-lxml",
    "ipython",
    "pillow",
   
]
